# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: marcelmichau
  imageName: fakesurveygeneratorapi

steps:
- script: dotnet build FakeSurveyGenerator.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test FakeSurveyGenerator.Domain.Tests/FakeSurveyGenerator.Domain.Tests.csproj --logger trx
  displayName: 'Run Unit Tests'

- script: dotnet test FakeSurveyGenerator.API.Tests.Integration/FakeSurveyGenerator.API.Tests.Integration.csproj --logger trx
  displayName: 'Run Integration Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: |
    docker build -t $(dockerId)/$(imageName) -f FakeSurveyGenerator.API/Dockerfile .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)
