apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-ui
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf # mount nginx-conf volumn to /etc/nginx
              subPath: nginx.conf
              readOnly: true
              name: nginx-conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "..fullname" . }}-ui-config-map # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
