apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-api-config-map
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ConnectionStrings__SurveyContext: Server={{ include "..fullname" . }}-database;Database={{ .Values.api.config.database }};user id={{ .Values.api.config.user }};pwd={{ .Values.api.config.password }};ConnectRetryCount=0